strictness: medium
doc-warnings: true
test-warnings: false
max-line-length: 120
ignore-paths:
  - docs
  - docs_theme
  - extra
ignore-patterns:
  - 'rummage(?:\\|/)lib(?:\\|/)gui(?:\\|/)gui\.py$'
pep257:
  disable:
    - D202
    - D203
    - D401
