name: deploy

on:
  push:
    tags:
    - '*'

jobs:

  documents:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build setuptools wheel
        python -m pip install -r requirements/docs.txt
    - name: Deploy documents
      run: |
        git config user.name facelessuser
        git config user.email "${{ secrets.GH_EMAIL }}"
        git remote add gh-token "https://${{ secrets.GH_TOKEN }}@github.com/facelessuser/Rummage.git"
        git fetch gh-token && git fetch gh-token gh-pages:gh-pages
        python -m mkdocs gh-deploy -v --clean --remote-name gh-token
        git push gh-token gh-pages

  pypi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Package
        run: |
          pip install --upgrade build
          python -m build -s
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PWD }}
